package standards

import "github.com/arvingarciabtw/ditto/internal/keyboard/base"

var KanaLayout = map[string]string{
	"1": "ぬ", "2": "ふ", "3": "あ", "4": "う", "5": "え",
	"6": "お", "7": "や", "8": "ゆ", "9": "よ", "0": "わ",
	"-": "ほ", "^": "へ",

	"Q": "た", "W": "て", "E": "い", "R": "す", "T": "か",
	"Y": "ん", "U": "な", "I": "に", "O": "ら", "P": "せ",
	"@": "゛", "[": "゜",

	"A": "ち", "S": "と", "D": "し", "F": "は", "G": "き",
	"H": "く", "J": "ま", "K": "の", "L": "り",
	";": "れ", ":": "け", "]": "む",

	"Z": "つ", "X": "さ", "C": "そ", "V": "ひ", "B": "こ",
	"N": "み", "M": "も",
	",": "ね", ".": "る", "/": "め", "\\": "ろ",
}

var KanaSmallMap = map[string]string{
	"3": "ぁ", "4": "ぅ", "5": "ぇ", "6": "ぉ",
	"7": "ゃ", "8": "ゅ", "9": "ょ", "0": "を",
	"E": "ぃ", "Z": "っ",
	"[": "「", "]": "」",
	",": "、", ".": "。", "/": "・",
}

var SizesJIS = map[int][][]base.Key{
	60:  size60JIS,
	65:  size65JIS,
	75:  size75JIS,
	80:  size80JIS,
	96:  size96JIS,
	100: size100JIS,
}

var size60JIS = [][]base.Key{
	{
		{Label: "全半", Width: base.U1p5, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<", Width: base.U1, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
	},
	{
		base.KeyTab, base.KeyQ, base.KeyW, base.KeyE, base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		{Label: "Ent↵", Width: base.U2, Finger: base.KeyEnterISO.Finger, EvCode: base.KeyEnterISO.EvCode, Gap: base.KeyEnterISO.Gap},
	},
	{
		base.KeyCapsLock, base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		{Label: base.KeyEnterISOBlank.Label, Width: base.U1p75, Finger: base.KeyEnterISOBlank.Finger, EvCode: base.KeyEnterISOBlank.EvCode},
	},
	{
		{Label: "Shift", Width: base.U2p5, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shift", Width: base.U2p75, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta, base.KeyLeftAlt, base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3p5, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana, base.KeyRightAlt, base.KeyRightMeta, base.KeyFn, base.KeyRightCtrl,
	},
}

var size65JIS = [][]base.Key{
	{
		{Label: "全半", Width: base.U1p5, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<", Width: base.U1, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
		{Label: base.KeyLightsToggle.Label, Width: base.KeyLightsToggle.Width, Finger: base.Any, EvCode: base.KeyLightsToggle.EvCode},
	},
	{
		base.KeyTab, base.KeyQ, base.KeyW, base.KeyE, base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		{Label: "Ent↵", Width: base.U2, Finger: base.KeyEnterISO.Finger, EvCode: base.KeyEnterISO.EvCode, Gap: base.KeyEnterISO.Gap},
		{Label: base.KeyHome.Label, Width: base.KeyHome.Width, Finger: base.Any, EvCode: base.KeyHome.EvCode},
	},
	{
		base.KeyCapsLock, base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		{Label: base.KeyEnterISOBlank.Label, Width: base.U1p75, Finger: base.KeyEnterISOBlank.Finger, EvCode: base.KeyEnterISOBlank.EvCode},
		{Label: base.KeyPageUp.Label, Width: base.KeyPageUp.Width, Finger: base.Any, EvCode: base.KeyPageUp.EvCode},
	},
	{
		{Label: "Shf", Width: base.U1p75, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shft", Width: base.U2, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
		base.KeyUp,
		{Label: base.KeyPageDown.Label, Width: base.KeyPageDown.Width, Finger: base.Any, EvCode: base.KeyPageDown.EvCode},
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta,
		{Label: base.KeyLeftAlt.Label, Width: base.U1, Finger: base.KeyLeftAlt.Finger, EvCode: base.KeyLeftAlt.EvCode},
		base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3p5, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana,
		{Label: base.KeyRightAlt.Label, Width: base.U1, Finger: base.KeyRightAlt.Finger, EvCode: base.KeyRightAlt.EvCode},
		base.KeyFn, base.KeyRightCtrl, base.KeyLeft, base.KeyDown, base.KeyRight,
	},
}

var size75JIS = [][]base.Key{
	{
		base.KeyEsc, base.KeyF1, base.KeyF2, base.KeyF3, base.KeyF4, base.KeyF5, base.KeyF6, base.KeyF7, base.KeyF8, base.KeyF9, base.KeyF10, base.KeyF11, base.KeyF12,
		{Label: base.KeyPrintScreen.Label, Width: base.KeyPrintScreen.Width, Finger: base.Any, EvCode: base.KeyPrintScreen.EvCode},
		{Label: base.KeyDelete.Label, Width: base.KeyDelete.Width, Finger: base.Any, EvCode: base.KeyDelete.EvCode},
		{Label: base.KeyLightsToggle.Label, Width: base.KeyLightsToggle.Width, Finger: base.Any, EvCode: base.KeyLightsToggle.EvCode},
	},
	{
		{Label: "全", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<", Width: base.U1, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
		{Label: base.KeyPageUp.Label, Width: base.KeyPageUp.Width, Finger: base.Any, EvCode: base.KeyPageUp.EvCode},
	},
	{
		base.KeyTab, base.KeyQ, base.KeyW, base.KeyE, base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		base.KeyEnterISO,
		{Label: base.KeyPageDown.Label, Width: base.KeyPageDown.Width, Finger: base.Any, EvCode: base.KeyPageDown.EvCode},
	},
	{
		base.KeyCapsLock, base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		base.KeyEnterISOBlank,
		{Label: base.KeyHome.Label, Width: base.KeyHome.Width, Finger: base.Any, EvCode: base.KeyHome.EvCode},
	},
	{
		{Label: "Shf", Width: base.U1p75, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shf", Width: base.U1p75, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
		base.KeyUp,
		{Label: base.KeyEnd.Label, Width: base.KeyEnd.Width, Finger: base.Any, EvCode: base.KeyEnd.EvCode},
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta,
		{Label: base.KeyLeftAlt.Label, Width: base.U1, Finger: base.KeyLeftAlt.Finger, EvCode: base.KeyLeftAlt.EvCode},
		base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana,
		{Label: base.KeyRightAlt.Label, Width: base.U1, Finger: base.KeyRightAlt.Finger, EvCode: base.KeyRightAlt.EvCode},
		base.KeyFn, base.KeyRightCtrl, base.KeyLeft,
		base.KeyDown, base.KeyRight,
	},
}

var size80JIS = [][]base.Key{
	{
		base.KeyEsc,
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyF1, base.KeyF2, base.KeyF3, base.KeyF4, base.KeyBlank, base.KeyF5, base.KeyF6, base.KeyF7, base.KeyF8, base.KeyBlank, base.KeyF9, base.KeyF10,
		base.KeyF11, base.KeyF12,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyPrintScreen, base.KeyScrollLock, base.KeyLightsToggle,
	},
	{
		{Label: "全半", Width: base.U1p5, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<-", Width: base.U1p5, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyInsert, base.KeyHome, base.KeyPageUp,
	},
	{
		{Label: "Tab", Width: base.U2p5, Finger: base.KeyTab.Finger, EvCode: base.KeyTab.EvCode},
		base.KeyQ, base.KeyW, base.KeyE,
		base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		base.KeyEnterISO,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyDelete, base.KeyEnd, base.KeyPageDown,
	},
	{
		{Label: base.KeyCapsLock.Label, Width: base.U2p75, Finger: base.KeyCapsLock.Finger, EvCode: base.KeyCapsLock.EvCode},
		base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		base.KeyEnterISOBlank,
		{Label: base.KeyBlank.Label, Width: base.U2, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: true, Leftless: false},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: false, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: false, Leftless: false},
	},
	{
		{Label: "Shift", Width: base.U2p5, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shift", Width: base.U3, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: true, Leftless: false},
		{Label: base.KeyBlank.Label, Width: base.U0p75, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyUp,
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta, base.KeyLeftAlt,
		base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3p75, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana,
		base.KeyRightAlt, base.KeyRightMeta, base.KeyFn, base.KeyRightCtrl,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyLeft, base.KeyDown, base.KeyRight,
	},
}

var size96JIS = [][]base.Key{
	{
		base.KeyEsc, base.KeyF1, base.KeyF2, base.KeyF3, base.KeyF4, base.KeyF5, base.KeyF6, base.KeyF7, base.KeyF8, base.KeyF9, base.KeyF10, base.KeyF11, base.KeyF12,
		{Label: base.KeyDelete.Label, Width: base.KeyDelete.Width, Finger: base.Any, EvCode: base.KeyDelete.EvCode},
		{Label: base.KeyHome.Label, Width: base.KeyHome.Width, Finger: base.Any, EvCode: base.KeyHome.EvCode},
		{Label: base.KeyEnd.Label, Width: base.KeyEnd.Width, Finger: base.Any, EvCode: base.KeyEnd.EvCode},
		{Label: base.KeyPageUp.Label, Width: base.KeyPageUp.Width, Finger: base.Any, EvCode: base.KeyPageUp.EvCode},
		{Label: base.KeyPageDown.Label, Width: base.KeyPageDown.Width, Finger: base.Any, EvCode: base.KeyPageDown.EvCode},
		{Label: base.KeyLightsToggle.Label, Width: base.KeyLightsToggle.Width, Finger: base.Any, EvCode: base.KeyLightsToggle.EvCode},
	},
	{
		{Label: "全", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<", Width: base.U1, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
		base.KeyNumLock, base.KeyPadSlash, base.KeyPadAsterisk, base.KeyPadMinus,
	},
	{
		base.KeyTab, base.KeyQ, base.KeyW, base.KeyE, base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		base.KeyEnterISO, base.KeyPad7, base.KeyPad8, base.KeyPad9, base.KeyPadPlus,
	},
	{
		base.KeyCapsLock, base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		base.KeyEnterISOBlank, base.KeyPad4, base.KeyPad5, base.KeyPad6,
		{Label: base.KeyPadPlus.Label, Width: base.KeyPadPlus.Width, Finger: base.KeyPadPlus.Finger, EvCode: base.KeyPadPlus.EvCode},
	},
	{
		{Label: "Shf", Width: base.U1p75, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shf", Width: base.U1p75, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
		base.KeyUp,
		base.KeyPad1, base.KeyPad2, base.KeyPad3, base.KeyPadEnter,
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta,
		{Label: base.KeyLeftAlt.Label, Width: base.U1, Finger: base.KeyLeftAlt.Finger, EvCode: base.KeyLeftAlt.EvCode},
		base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana,
		{Label: base.KeyRightAlt.Label, Width: base.U1, Finger: base.KeyRightAlt.Finger, EvCode: base.KeyRightAlt.EvCode},
		base.KeyFn, base.KeyRightCtrl, base.KeyLeft,
		base.KeyDown, base.KeyRight,
		{Label: base.KeyPad0.Label, Width: base.U1, Finger: base.Middle, EvCode: base.KeyPad0.EvCode},
		base.KeyPadDot,
		{Label: base.KeyPadEnter.Label, Width: base.KeyPadEnter.Width, Finger: base.KeyPadEnter.Finger, EvCode: base.KeyPadEnter.EvCode},
	},
}

var size100JIS = [][]base.Key{
	{
		base.KeyEsc,
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyF1, base.KeyF2, base.KeyF3, base.KeyF4, base.KeyBlank, base.KeyF5, base.KeyF6, base.KeyF7, base.KeyF8, base.KeyBlank, base.KeyF9, base.KeyF10,
		base.KeyF11, base.KeyF12,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyPrintScreen, base.KeyScrollLock, base.KeyLightsToggle,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: true},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
	},
	{
		{Label: "全半", Width: base.U1p5, Finger: base.Pinky, EvCode: base.KeyApostrophe.EvCode},
		base.Key1, base.Key2, base.Key3, base.Key4, base.Key5, base.Key6, base.Key7, base.Key8, base.Key9, base.Key0, base.KeyMinus,
		{Label: "^", Width: base.U1, Finger: base.Pinky, EvCode: base.KeyBlank.EvCode},
		base.KeyYen,
		{Label: "<-", Width: base.U1p5, Finger: base.KeyBackspace.Finger, EvCode: base.KeyBackspace.EvCode},
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyInsert, base.KeyHome, base.KeyPageUp,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyNumLock, base.KeyPadSlash, base.KeyPadAsterisk, base.KeyPadMinus,
	},
	{
		{Label: "Tab", Width: base.U2p5, Finger: base.KeyTab.Finger, EvCode: base.KeyTab.EvCode},
		base.KeyQ, base.KeyW, base.KeyE,
		base.KeyR, base.KeyT, base.KeyY, base.KeyU, base.KeyI, base.KeyO, base.KeyP,
		{Label: "@", Width: base.U1, Finger: base.KeyLeftBrace.Finger, EvCode: base.KeyLeftBrace.EvCode},
		{Label: "[", Width: base.U1, Finger: base.KeyRightBrace.Finger, EvCode: base.KeyRightBrace.EvCode},
		base.KeyEnterISO,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyDelete, base.KeyEnd, base.KeyPageDown,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyPad7, base.KeyPad8, base.KeyPad9, base.KeyPadPlus,
	},
	{
		{Label: base.KeyCapsLock.Label, Width: base.U2p75, Finger: base.KeyCapsLock.Finger, EvCode: base.KeyCapsLock.EvCode},
		base.KeyA, base.KeyS, base.KeyD, base.KeyF, base.KeyG, base.KeyH, base.KeyJ, base.KeyK, base.KeyL, base.KeySemicolon, base.KeyColon,
		base.KeyRightBrace,
		base.KeyEnterISOBlank,
		{Label: base.KeyBlank.Label, Width: base.U2, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: true, Leftless: false},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: false, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.U2, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: false, Leftless: false},
		base.KeyPad4, base.KeyPad5, base.KeyPad6,
		{Label: base.KeyPadPlus.Label, Width: base.KeyPadPlus.Width, Finger: base.KeyPadPlus.Finger, EvCode: base.KeyPadPlus.EvCode},
	},
	{
		{Label: "Shift", Width: base.U2p5, Finger: base.KeyLeftShiftISO.Finger, EvCode: base.KeyLeftShiftISO.EvCode},
		base.KeyZ, base.KeyX, base.KeyC, base.KeyV, base.KeyB, base.KeyN, base.KeyM, base.KeyComma, base.KeyDot, base.KeySlash,
		{Label: base.KeyBackslash.Label, Width: base.U1, Finger: base.KeyBackslash.Finger, EvCode: base.KeyBackslash.EvCode},
		{Label: "Shift", Width: base.U3, Finger: base.KeyRightShiftISO.Finger, EvCode: base.KeyRightShiftISO.EvCode},
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true, Rightless: true, Leftless: false},
		{Label: base.KeyBlank.Label, Width: base.U0p75, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyUp,
		{Label: base.KeyBlank.Label, Width: base.U1, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Rightless: true, Leftless: true},
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyPad1, base.KeyPad2, base.KeyPad3, base.KeyPadEnter,
	},
	{
		base.KeyLeftCtrl, base.KeyLeftMeta, base.KeyLeftAlt,
		base.KeyMuhenkan,
		{Label: base.KeySpace.Label, Width: base.U3p75, Finger: base.KeySpace.Finger, EvCode: base.KeySpace.EvCode},
		base.KeyHenkan, base.KeyKana,
		base.KeyRightAlt, base.KeyRightMeta, base.KeyFn, base.KeyRightCtrl,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode},
		base.KeyLeft, base.KeyDown, base.KeyRight,
		{Label: base.KeyBlank.Label, Width: base.KeyBlank.Width, Finger: base.KeyBlank.Finger, EvCode: base.KeyBlank.EvCode, Gap: true},
		base.KeyPad0, base.KeyPadDot,
		{Label: base.KeyPadEnter.Label, Width: base.KeyPadEnter.Width, Finger: base.KeyPadEnter.Finger, EvCode: base.KeyPadEnter.EvCode},
	},
}
